services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped

    volumes:
      - ${CONFIGS_DIR}/adguard/work:/opt/adguardhome/work
      - ${CONFIGS_DIR}/adguard/conf:/opt/adguardhome/conf

    ports:
      - 53:53/tcp
      - 53:53/udp
      #- 67:67/udp # DHCP
      - 3000:3000/tcp # Web UI

    networks:
      - docker-network
      
networks:
  docker-network:
    external: true
